src/Entity/Classroom.php
<?php

namespace App\Entity;

use App\Repository\ClassroomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ClassroomRepository::class)]
class Classroom
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    private ?Uuid $id;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 5,
        minMessage: 'The name must be at least 5 characters long'
    )]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Assert\Url()]
    private ?string $gitlabUrl = null;

    #[ORM\Column]
    private ?int $gitlabGroupId = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'classrooms')]
    private Collection $users;

    /**
     * @var Collection<int, Assignment>
     */
    #[ORM\OneToMany(targetEntity: Assignment::class, mappedBy: 'classroom')]
    private Collection $assignments;

    #[ORM\ManyToOne(inversedBy: 'myclassrooms')]
    private ?User $owner = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->assignments = new ArrayCollection();
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getGitlabUrl(): ?string
    {
        return $this->gitlabUrl;
    }

    public function setGitlabUrl(string $gitlabUrl): static
    {
        $this->gitlabUrl = $gitlabUrl;

        return $this;
    }

    public function getGitlabGroupId(): ?int
    {
        return $this->gitlabGroupId;
    }

    public function setGitlabGroupId(int $gitlabGroupId): static
    {
        $this->gitlabGroupId = $gitlabGroupId;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        $this->users->removeElement($user);

        return $this;
    }

    /**
     * @return Collection<int, Assignment>
     */
    public function getAssignments(): Collection
    {
        return $this->assignments;
    }

    public function addAssignment(Assignment $assignment): static
    {
        if (!$this->assignments->contains($assignment)) {
            $this->assignments->add($assignment);
            $assignment->setClassroom($this);
        }

        return $this;
    }

    public function removeAssignment(Assignment $assignment): static
    {
        if ($this->assignments->removeElement($assignment)) {
            // set the owning side to null (unless already changed)
            if ($assignment->getClassroom() === $this) {
                $assignment->setClassroom(null);
            }
        }

        return $this;
    }

    public function getStudents(): Collection
    {
        return new ArrayCollection(array_filter($this->users->toArray(), function ($user) {
            return $user->hasRole('ROLE_STUDENT');
        }));
    }

    public function getTeachers(): Collection
    {
        return new ArrayCollection(array_filter($this->users->toArray(), function ($user) {
            return $user->hasRole('ROLE_TEACHER');
        }));
    }

    public function nbStudents(): int
    {
        return count($this->getStudents());
    }

    public function nbTeachers(): int
    {
        // on ajoute le propriétaire de la classe
        return count($this->getTeachers()) + 1;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
class User implements UserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $username = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(type: Types::BIGINT)]
    private ?string $gitlabUserId = null;

    #[ORM\Column(length: 255)]
    #[Assert\Url()]
    private ?string $avatarUrl = null;

    #[ORM\Column(length: 255)]
    #[Assert\Email()]
    private ?string $email = null;

    /**
     * @var Collection<int, Classroom>
     */
    #[ORM\ManyToMany(targetEntity: Classroom::class, mappedBy: 'users')]
    private Collection $classrooms;

    /**
     * @var Collection<int, Assignment>
     */
    #[ORM\ManyToMany(targetEntity: Assignment::class, mappedBy: 'users')]
    private Collection $assignments;

    /**
     * @var Collection<int, Exercise>
     */
    #[ORM\OneToMany(targetEntity: Exercise::class, mappedBy: 'student')]
    private Collection $exercises;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $accessToken = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $refreshToken = null;

    #[ORM\Column(nullable: true)]
    private ?int $expiresToken = null;

    #[ORM\Column(nullable: true)]
    private ?int $createdAtToken = null;

    /**
     * @var Collection<int, Classroom>
     */
    #[ORM\OneToMany(targetEntity: Classroom::class, mappedBy: 'owner')]
    private Collection $myclassrooms;

    public function __construct()
    {
        $this->classrooms = new ArrayCollection();
        $this->assignments = new ArrayCollection();
        $this->exercises = new ArrayCollection();
        $this->myclassrooms = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function hasRole(string $role): bool
    {
        return in_array($role, $this->getRoles());
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getGitlabUserId(): ?string
    {
        return $this->gitlabUserId;
    }

    public function setGitlabUserId(string $gitlabUserId): static
    {
        $this->gitlabUserId = $gitlabUserId;

        return $this;
    }

    public function getAvatarUrl(): ?string
    {
        return $this->avatarUrl;
    }

    public function setAvatarUrl(string $avatarUrl): static
    {
        $this->avatarUrl = $avatarUrl;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getClassrooms(): array
    {
        return array_merge($this->classrooms->toArray(), $this->myclassrooms->toArray());
    }

    public function addClassroom(Classroom $classroom): static
    {
        if (!$this->classrooms->contains($classroom)) {
            $this->classrooms->add($classroom);
            $classroom->addUser($this);
        }
        return $this;
    }

    public function removeClassroom(Classroom $classroom): static
    {
        if ($this->classrooms->removeElement($classroom)) {
            $classroom->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Assignment>
     */
    public function getAssignments(): Collection
    {
        return $this->assignments;
    }

    public function addAssignment(Assignment $assignment): static
    {
        if (!$this->assignments->contains($assignment)) {
            $this->assignments->add($assignment);
        }

        return $this;
    }

    public function removeAssignment(Assignment $assignment): static
    {
        $this->assignments->removeElement($assignment);

        return $this;
    }

    /**
     * @return Collection<int, Exercise>
     */
    public function getExercises(): Collection
    {
        return $this->exercises;
    }

    public function addExercise(Exercise $exercise): static
    {
        if (!$this->exercises->contains($exercise)) {
            $this->exercises->add($exercise);
            $exercise->setStudent($this);
        }

        return $this;
    }

    public function removeExercise(Exercise $exercise): static
    {
        if ($this->exercises->removeElement($exercise)) {
            // set the owning side to null (unless already changed)
            if ($exercise->getStudent() === $this) {
                $exercise->setStudent(null);
            }
        }

        return $this;
    }

    public function getAccessToken(): ?string
    {
        return $this->accessToken;
    }

    public function setAccessToken(?string $accessToken): static
    {
        $this->accessToken = $accessToken;

        return $this;
    }

    public function getRefreshToken(): ?string
    {
        return $this->refreshToken;
    }

    public function setRefreshToken(?string $refreshToken): static
    {
        $this->refreshToken = $refreshToken;

        return $this;
    }

    public function getExpiresToken(): ?int
    {
        return $this->expiresToken;
    }

    public function setExpiresToken(?int $expiresToken): static
    {
        $this->expiresToken = $expiresToken;

        return $this;
    }

    public function getCreatedAtToken(): ?int
    {
        return $this->createdAtToken;
    }

    public function setCreatedAtToken(?int $createdAtToken): static
    {
        $this->createdAtToken = $createdAtToken;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getUserIdentifier();
    }

    /**
     * @return Collection<int, Classroom>
     */
    public function getMyclassrooms(): Collection
    {
        return $this->myclassrooms;
    }

    public function addMyclassroom(Classroom $myclassroom): static
    {
        if (!$this->myclassrooms->contains($myclassroom)) {
            $this->myclassrooms->add($myclassroom);
            $myclassroom->setOwner($this);
        }

        return $this;
    }

    public function removeMyclassroom(Classroom $myclassroom): static
    {
        if ($this->myclassrooms->removeElement($myclassroom)) {
            // set the owning side to null (unless already changed)
            if ($myclassroom->getOwner() === $this) {
                $myclassroom->setOwner(null);
            }
        }

        return $this;
    }
}

src/Form/ClassroomType.php
<?php

namespace App\Form;

use App\Entity\Classroom;
use App\Service\GitlabConnector;
use Gitlab\ResultPager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\UX\Autocomplete\Form\AsEntityAutocompleteField;

#[AsEntityAutocompleteField]
class ClassroomType extends AbstractType
{
    public function __construct(private GitlabConnector $connector)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $pager = new ResultPager($this->connector->getClient());
        // TODO: top_level ou uniquement à partir d'un certain niveau
        $groups = $pager->fetchAll($this->connector->getClient()->groups(), 'all', [['owned' => true]]);
        $groupsObjects = [];
        $groupsObjects[0] = (object) ['id' => 0, 'name' => '--- No group parent ---'];
        foreach ($groups as $group) {
            $groupsObjects[] = (object) $group;
        }
        $builder
            ->add('name', TextType::class, [
                'attr' => [
                    'class' => 'block w-full rounded-md border-0 py-1.5 text-dark-1 shadow-sm ring-1 ring-inset
                    ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600
                    sm:text-sm sm:leading-6',
                    'placeholder' => 'Classroom Name'
                ],
                'label' => 'Classroom name',
                'label_attr' => ['class' => 'block text-sm font-medium leading-6 text-gray-900'],
            ])
            ->add('parentGroup', ChoiceType::class, [
                'choices' => $groupsObjects,
                'choice_value' => 'id',
                'choice_label' => 'name',
                'mapped' => false,
                'autocomplete' => true,
                'attr' => [
                    'class' => 'text-dark-1',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Classroom::class,
        ]);
    }
}

templates/classroom/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<header class="py-10">
    <h4 class="font-extrabold text-white pl-10">{{ "New Classroom" | trans }}</h4>
</header>

<main
        class="rounded-3xl bg-dark-2 p-10"
><section>
        {{ form_start(form) }}
            <div class="space-y-12">
                <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 pb-12 md:grid-cols-3">
                    <div>
                        <h2 class="text-base font-semibold leading-7 text-gray-900">{{ "Classroom" | trans }}</h2>
                        <p class="mt-1 text-sm leading-6 text-gray-600">{{ "Please enter the details about the Classroom to create" | trans }}</p>
                    </div>

                    <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2">
                        <div class="sm:col-span-4">
                            {{ form_label(form.name) }} {{ form_errors(form.name) }}
                            <div class="mt-2">
                                {{ form_widget(form.name) }}
                            </div>
                            <p class="mt-3 text-sm leading-6 text-gray-600">{{ "The Classroom name will be used as a GitLab Group name" | trans }}.</p>
                        </div>

                        <div class="col-span-full">
                            {{ form_label(form.parentGroup) }} - {{ "You can search for a group by typing in the selection field" | trans }}.
                            <div class="relative mt-2">
                                {{ form_widget(form.parentGroup) }}
                            </div>

                            <p class="mt-3 text-sm leading-6 text-gray-600">{{ "A new GitLab Group with the Classroom name will be created in the selected GitLab Group" | trans }}.</p>
                            <p class="mt-3 text-sm leading-6 text-gray-600">{{ "If no GitLab Group is selected, the Classroom will be created at the root of GitLab" | trans }}.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="mt-6 flex items-center justify-end gap-x-6">
                <a href="{{ path('app_dashboard') }}" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                    {{ "Cancel" | trans }}
                </a>
                <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                    {{ "Create" | trans }}</button>
            </div>
    {{ form_end(form) }}

    </section>
</main>

{% endblock %}

templates/classroom/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <header class="py-10">
        <h4 class="font-extrabold text-white pl-10">{{ "Classroom" | trans }} {{ classroom.name }}</h4>
        <p class="pl-14"><span class="i-mdi-teacher" title=""></span> {{ classroom.owner}} </p>
        <p class="pl-16">
            {% for teacher in classroom.teachers %}
                {{ teacher.userIdentifier }}
                {% if loop.last == false %}-{% endif%}
            {% endfor %}
        </p>
        {% for flash in app.flashes('error') %}
            <section class="pl-10 danger-alert" role="alert">
                {{ flash }}
            </section>
        {% endfor %}
    </header>
    <main class="rounded-3xl bg-dark-2 p-10"><section x-data="filterStudentsFeature()">
            <script type="application/javascript">
                async function copyToClipboard(element){
                    const relativeUrl = element.getAttribute('data-clipboard');
                    const url = `${window.location.protocol}//${window.location.host}${relativeUrl}`;
                    await navigator.clipboard.writeText(url);
                }

                function filterStudentsFeature() {
                    return {
                        filter: '',
                        filterStudents(studentName) {
                            return studentName.toLowerCase().includes(this.filter.toLowerCase());
                        }
                    }
                }
            </script>

            <div class="mb-6">
                <div class="flex flex-row justify-between gap-2" x-data="{ open: false }">
                    <a type="button" href="{{ classroom.gitlabUrl }}" target="_blank" class="btn-primary">
                        <span class="i-lucide-gitlab text-orange-dark"></span>
                        {{ "Open in" | trans }} GitLab
                    </a>
                    {% if app.user == classroom.owner %}
                        {% set action =  path('app_classroom_delete', {'id': classroom.id})  %}
                        <a @click.prevent="open = !open"
                           :aria-checked="open"
                           role="checkbox"
                           href="{{ path('app_classroom_delete', {'id': classroom.id}) }}"
                           class="btn-danger">
                            <span class="i-lucide-trash"></span>{{ "Delete" | trans }}
                        </a>
                        {% include 'components/validationForm.html.twig' %}
                    {% endif %}
                </div>
            </div>

            <div class="flex md:flex-row flex-col gap-4 justify-between items-center border-b border-b-dark-4 py-8">
                <div class="flex-1">
                    <h3 class="text-base font-semibold leading-6 text-gray-900 mb-2">{{ "students" | trans }}</h3>
                    <p class="text-base text-dark-7 flex flex-row gap-2">
                        <span class="i-lucide-users"></span>
                        <span>{{ classroom.students | length }}</span> {{ "students" | trans }}.
                    </p>
                </div>

                <button type="button" onclick="copyToClipboard(this)" data-clipboard="{{ path('app_classroom_join', {'id': classroom.id}) }}" class="btn-primary">
                    <span class="i-lucide-link"></span>
                    {{ "Copy Join Link" | trans }}
                </button>

                <div>
                    <div class="relative rounded-2xl">
                        <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-4">
                            <span class="i-mdi-users"></span>
                        </div>
                        <input x-model="filter"
                               type="text"
                               class="block w-full bg-dark-4 rounded-2xl border-0 px-3 py-3 pl-12 text-white ring-1 ring-inset ring-dark-9 placeholder:text-dark-6 hover:ring-2 hover:ring-inset hover:ring-primary-100 focus:ring-4 focus:ring-inset focus:ring-primary-160"
                               placeholder="{{ "Search for Students" | trans }}"
                        >
                    </div>
                </div>
            </div>
            {% if classroom.students %}
            <ul role="list" class="md:grid flex flex-col grid-cols-3 gap-6 mt-6 border-b border-b-dark-4 pb-6">
                {%for student in classroom.students %}
                <li x-show="filterStudents('{{ student.userIdentifier }}')">
                    <div class="student-card">
                        <img class="avatar" src="{{ student.avatarUrl }}" alt="Student avatar">
                        <div class="student-details">
                            <a href="{{ path('app_classroom_student_view', { 'id' : classroom.id , 'username' : student.userIdentifier}) }}">{{ student.userIdentifier }}</a>
                            <div class="email">
                                <span class="i-lucide-send"></span>
                                <span class="ml-2">{{ student.email }}</span>
                            </div>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% endif %}

            <div class="flex flex-row justify-between border-b border-b-dark-4 py-8">
                <div>
                    <h3 class="text-base font-semibold leading-6 text-gray-900 mb-2">{{ "Assignments of the current classroom" | trans }}</h3>
                </div>
                <a href="{{ path('app_classroom_assignment_new', {'id': classroom.id}) }}" type="button" class="btn-primary">
                    <span class="i-mdi-add"></span>
                    {{ "New Assignment" | trans }}
                </a>
            </div>
            {% if assignments %}
            <ul role="list" class="md:grid flex flex-col grid-cols-3 gap-6 mt-6">
                {% for assignment in assignments %}
                <li>
                    <div class="assignment-card">
                        <a href="{{ path('app_assignment_view', { 'id': assignment.id }) }}" class="assignment-header">
                            <div>
                                <span class="i-lucide-brackets"></span>
                            </div>
                            <span>{{ assignment.name }}</span>
                        </a>
                        <div class="flex flex-row items-center gap-4 pl-8 py-2">
                            <span class="i-mdi-users"></span>
                            <span> {{ assignment.exercises | length }} / {{ classroom.students | length }} {{ "Students accepted" | trans }}</span>
                        </div>
                        <button onclick="copyToClipboard(this)" data-clipboard="{{ path('app_assignment_accept', { 'id' : assignment.id }) }}" class="btn-primary rounded-3xl">
                            <span class="i-lucide-link"></span>
                            {{ "Copy Accept Link" | trans }}
                        </button>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </section>
    </main>
{% endblock %}

templates/classroom/viewStudent.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <header class="py-10">
        <h4 class="font-extrabold text-white pl-10">{{ "Classroom" | trans }}
            <a href="{{ path('app_classroom_view', {'id': classroom.id}) }}">{{ classroom.name}}</a>
            - {{ "Student" | trans }} {{ student.userIdentifier }}
        </h4>
    </header>
    <main class="rounded-3xl bg-dark-2 p-10"><section>
            <div class="flex flex-row justify-between border-b border-b-dark-4 py-8">
                <div>
                    <h3 class="text-base font-semibold leading-6 text-gray-900 mb-2">{{ student.userIdentifier }}</h3>
                    <p class="text-base text-dark-7">{{ "Accepted assignments of the classroom" | trans }} <span>{{ classroom.name }}</span>.</p>
                </div>
            </div>
            {% include 'components/listExercises.html.twig' %}
        </section>
    </main>
{% endblock %}